config/routes.rb
Rails.application.routes.draw do

  root 'application#show'

  resources :updater do
    collection do
      get 'check'
      post 'run'
    end
  end

  resources :configuration

end

app/controllers/application_controller.rb
# Diaspberry Wizard
#
# Copyright (C) 2016 Lukas Matt <lukas@zauberstuhl.de>,
# Matthias Neutzner <matthias.neutzner@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def show
  end
end

app/controllers/configuration_controller.rb
class ConfigurationController < ApplicationController
end

app/controllers/updater_controller.rb
# Diaspberry Wizard
#
# Copyright (C) 2016 Lukas Matt <lukas@zauberstuhl.de>,
# Matthias Neutzner <matthias.neutzner@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

class UpdaterController < ApplicationController
  include UpdaterHelper

  def check
    git = Rails.application.config.diaspora[:git]
    version = Gem::Version.new(latest_diaspora_version)
    installed = git.tags.last.name.sub(/^v/, '')

    if version > Gem::Version.new(installed)
      render json: {update: true, version: version.version}
    else
      render json: {update: false}
    end
  end

  def update
    UpdaterJob.perform_now
    render :index
  end
end

app/helpers/application_helper.rb
# Diaspberry Wizard
#
# Copyright (C) 2016 Lukas Matt <lukas@zauberstuhl.de>,
# Matthias Neutzner <matthias.neutzner@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

module ApplicationHelper
end

app/helpers/configuration_helper.rb
module ConfigurationHelper
end

app/helpers/updater_helper.rb
module UpdaterHelper
  require 'open-uri'

  # @return version number or nil
  def latest_diaspora_version
    dir = Rails.application.config.diaspora[:directory]
    feed = Rails.application.config.diaspora[:atomfeed]
    rss = SimpleRSS.parse open(feed)
    id = rss.items.first.id

    /\/v([\d\.]+?)$/.match(id)[1]
  end
end

app/views/application/show.html.haml
.container
  .page-header
    %h1= t('welcome.title', project: t('project'))

  %p= t('welcome.description', project: t('project'))

  %p= button_to t('button.get_started'), updater_index_path,
    {method: :get, class: 'btn btn-default'}

app/views/configuration/index.html.haml
.container
  .page-header
    %h1= t('welcome.title', project: t('project'))

  %p= t('configuration.description', project: t('project'))

  %form.form-horizontal{role: "form"}
    .form-group
      %label.col-sm-2.control-label{for: "url"} URL
      .col-sm-10
        %input#name.form-control{name: "url", placeholder: "http://localhost:3000", type: "text"}
    .form-group
      %label.col-sm-2.control-label{for: "name"} Pod Name
      .col-sm-10
        %input#name.form-control{name: "name", placeholder: "Diaspora*", type: "text"}

    .form-group
      %label.col-sm-2.control-label{for: "registration_enabled"} Enable Registrations
      .col-sm-10
        %input#email.form-control{name: "registration_enabled", type: "checkbox"}
    .form-group
      %label.col-sm-2.control-label{for: "chat_enabled"} Enable Chat
      .col-sm-10
        %input#email.form-control{name: "chat_enabled", type: "checkbox"}
    .form-group
      %label.col-sm-2.control-label{for: "camo_enabled"} Enable Camo
      .col-sm-10
        %input#email.form-control{name: "camo_enabled", type: "checkbox"}

    .form-group
      %label.col-sm-2.control-label{for: "welcome_message"} Welcome Message
      .col-sm-10
        %textarea.form-control{name: "welcome_message", rows: "4"} Hello %{username}, welcome to diaspora.

    .form-group
      .col-sm-10.col-sm-offset-2
        %input#submit.btn.btn-primary{:name => "submit", :type => "submit", :value => "Send"}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Diaspberry Wizard
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield

app/views/updater/index.html.haml
.container
  .page-header
    %h1= t('welcome.title', project: t('project'))

  %p= t('updater.description', project: t('project'))

  .spinner

  %p= button_to t('button.update'), run_updater_index_path,
    {method: :get, id: :update, class: 'btn btn-default', style: 'display: none'}

  %p= button_to t('button.next'), '/',
    {method: :get, id: :next, class: 'btn btn-default', style: 'display: none'}

= javascript_include_tag :updater